export const defaultValues = {
  Discerniendo: 1,
  Ensayando: 1,
  Involucrandome: 1,
  Practicando: 1,
  Receptivamente: 1,
  Relacionando: 1,
  Analiticamente: 1,
  Imparcialmente: 1,
  Sintiendo: 1,
  Aceptando: 1,
  Intuitivamente: 1,
  Abstracto: 1,
  Orientado_al_presente: 1,
  Aprendo_mas_de_la_experiencia: 1,
  Emotivo: 1,
  Arriesgado: 1,
  Productivamente: 1,
  Observando: 1,
  Reflexivamente: 1,
  Aprendo_mas_de_la_observacion: 1,
  Reservado: 1,
  Observando_: 1,
  Pensando: 1,
  Evaluando: 1,
  Logicamente: 1,
  Concreto: 1,
  Orientado_hacia_el_futuro: 1,
  Aprendo_mas_de_la_conceptualizacion: 1,
  Racional: 1,
  Haciendo: 1,
  Con_Cautela: 1,
  Cuestionando: 1,
  Activo: 1,
  Pragmatico: 1,
  Aprendo_mas_de_la_experimentacion: 1,
  Abierto: 1
}

export const words = [
  { value: 'Discerniendo', label: 'Discerniendo' },
  { value: 'Receptivamente', label: 'Receptivamente' },
  { value: 'Sintiendo', label: 'Sintiendo' },
  { value: 'Aceptando', label: 'Aceptando' },
  { value: 'Intuitivamente', label: 'Intuitivamente' },
  { value: 'Abstracto', label: 'Abstracto' },
  { value: 'Orientado_al_presente', label: 'Orientado al presente' },
  {
    value: 'Aprendo_mas_de_la_experiencia',
    label: 'Aprendo más de la experiencia'
  },
  { value: 'Emotivo', label: 'Emotivo' },
  { value: 'Ensayando', label: 'Ensayando' },
  { value: 'Relacionando', label: 'Relacionando' },
  { value: 'Arriesgado', label: 'Arriesgado' },
  { value: 'Productivamente', label: 'Productivamente' },
  { value: 'Observando', label: 'Observando' },
  { value: 'Reflexivamente', label: 'Reflexivamente' },
  {
    value: 'Aprendo_mas_de_la_observacion',
    label: 'Aprendo más de la observación'
  },
  { value: 'Reservado', label: 'Reservado' },
  { value: 'Involucrandome', label: 'Involucrándome' },
  { value: 'Analiticamente', label: 'Analíticamente' },
  { value: 'Observando_', label: 'Observando' },
  { value: 'Pensando', label: 'Pensando' },
  { value: 'Evaluando', label: 'Evaluando' },
  { value: 'Logicamente', label: 'Lógicamente' },
  { value: 'Concreto', label: 'Concreto' },
  { value: 'Orientado_hacia_el_futuro', label: 'Orientado hacia el futuro' },
  {
    value: 'Aprendo_mas_de_la_conceptualizacion',
    label: 'Aprendo más de la conceptualización'
  },
  { value: 'Racional', label: 'Racional' },
  { value: 'Practicando', label: 'Practicando' },
  { value: 'Imparcialmente', label: 'Imparcialmente' },
  { value: 'Haciendo', label: 'Haciendo' },
  { value: 'Con_Cautela', label: 'Con Cautela' },
  { value: 'Cuestionando', label: 'Cuestionando' },
  { value: 'Activo', label: 'Activo' },
  { value: 'Pragmatico', label: 'Pragmático' },
  {
    value: 'Aprendo_mas_de_la_experimentacion',
    label: 'Aprendo más de la experimentación'
  },
  { value: 'Abierto', label: 'Abierto' }
]
